### ISSUE TITLE
Issues initializing

### ISSUE THREAD

**Issue by davidbgonz** [ribelo/taskwarrior.nvim#1]
Hello. I happened to come across this plugin and I think it's a great idea. I'm following the steps for Packer and I'm running into some issues.

```
  use {
    'ribelo/taskwarrior.nvim',
    requires = 'nvim-telescope/telescope.nvim'
  }
```
Even without me adding the require to my init.lua file I am seeing this error:
```
Error detected while processing /home/<me>/.local/share/nvim/site/pack/packer/start/taskwarrior.nvim/plugin/taskwarrior_nvim.lua:                                         
E5113: Error while calling lua chunk: .../start/taskwarrior.nvim/lua/taskwarrior_nvim/autocmd.lua:41: attempt to index global 'M' (a nil value)                                  
stack traceback:                                                                                                                                                                 
        .../start/taskwarrior.nvim/lua/taskwarrior_nvim/autocmd.lua:41: in main chunk                                                                                            
        [C]: in function 'require'                                                                                                                                               
        ...k/packer/start/taskwarrior.nvim/lua/taskwarrior_nvim.lua:2: in main chunk                                                                                             
        [C]: in function 'require'                                                                                                                                               
        ...acker/start/taskwarrior.nvim/plugin/taskwarrior_nvim.lua:1: in main chunk
```

I'm not familiar enough with Lua to effectively debug this issue. I tried adding a local var for `M` to the beginning of the autocmd.lua file. I can see the Task cmd, but it does not work for me, so I do not think that was the solution.
When I add the require statement `require('taskwarrior.nvim').setup()` I get an error stating that module 'taskwarrior.nvim' is not found. I need to add `require('taskwarrior_nvim').setup()` which makes sense since that is how all the requires in your code is written.

**Comment by ribelo** [comment]
I'm sorry for not addressing this earlier, but the notification on GitHub slipped through, and as it often happens, "it worked on my machine." The changes in one file were not committed.
